---
- name: Setup environment
  hosts: app1
  become: true
  vars: 
   packages:
     - git
     - python3.12-venv
  tasks:
    - name: update packages in ubuntu deploy server
      apt:
        update_cache: yes

    - name: upgrade packages in ubuntu deploy server
      apt:
        upgrade: yes
        
    - name: Install packages in ubuntu deploy server
      apt:
        name: "{{ packages }}"
        state: present

    - name: git clone the repository
      git:
        repo: https://github.com/TWhilst/Flask-monitoring-dashboard.git
        version: main
        single_branch: true
        dest: /home/ubuntu/flask
    
    # this is used to setup the python virtual environment for python and pip commands
    - name: Setup python virtual environment
      shell:  |
        python3 -m venv /home/ubuntu/env/teton
      # it is important to use bin/bash as the shell to ensure the virtual environment is activated correctly
      args:
        executable: /bin/bash

    - name: Install Python dependencies from requirements.txt
      ansible.builtin.pip:
        requirements: /home/ubuntu/flask/requirements.txt # Path to your requirements.txt file
        virtualenv: /home/ubuntu/env/teton # Tells pip to install into this venv
        virtualenv_python: python3
    
    - name: Run Flask app 
      cmd: /home/ubuntu/env/teton/bin/python home/ubuntu/flask/app.py
      args:
        chdir: /home/ubuntu/flask 
    
    # - name: Install flask and run the python app
    #   shell: |
    #     cd flask 
    #     pip install -r requirements.txt
    #     python app.py
    #   args:
    #     executable: /bin/bash
# source /home/ubuntu/env/teton/bin/activate
#         cd flask
#         pip install -r requirements.txt
#         python app.py
