---
- name: Setup Gunicorn for Flask application
  hosts: app1
  become: true
  tasks:
    - name: install Gunicorn
      ansible.builtin.pip:
        name: gunicorn # Path to your requirements.txt file
        virtualenv: /home/ubuntu/env/teton # Tells pip to install into this venv
        virtualenv_python: python3

    - name: Create or update web server gateway interface file (wsgi.py)
      ansible.builtin.copy:
        dest: /home/ubuntu/flask/wsgi.py
        content: |
          from app import app

          if __name__ == "__main__":
              app.run()

    - name: Start Gunicorn for testing (NON-BLOCKING, NOT FOR PRODUCTION)
      ansible.builtin.command: /home/ubuntu/env/teton/bin/gunicorn --bind 0.0.0.0:5000 wsgi:app
      args:
        chdir: /home/ubuntu/flask # Change to the application directory
      async: 600   # Run in the background for up to 600 seconds (10 minutes)
      poll: 0

# created and edited 02-setup-gunicorn.yml